SELECT
  'BfMAe6Itzgt' AS data_set,
  TO_CHAR(event_date, 'YYYYMM') AS period,
  SUM(CASE WHEN HIV_TEST_M THEN 1 ELSE 0 END) AS tests_performed,
  SUM(CASE WHEN HIV_TEST_POS_M THEN 1 ELSE 0 END) AS tests_positive,
  SUM(CASE WHEN HIV_HTS_CLIENTS_TESTED_HIV_Y THEN 1 ELSE 0 END) AS hts_tested,
  SUM(CASE WHEN HIV_HTS_CLIENT_HIV_POSITIVE_Y THEN 1 ELSE 0 END) AS hts_positive,
  SUM(CASE WHEN HIV_NEW_CASES_M THEN 1 ELSE 0 END) AS new_cases,
  SUM(CASE WHEN HIV_NEW_HIV_CASES_STARTED_ART_M THEN 1 ELSE 0 END) AS new_cases_on_art,
  SUM(CASE WHEN HIV_ART_M THEN 1 ELSE 0 END) AS patients_on_art,
  SUM(CASE WHEN HIV_VIRSUPP_M THEN 1 ELSE 0 END) AS virally_suppressed,
  SUM(CASE WHEN HIV_STI_CLIENTS_SYPHILIS_TESTED_Y THEN 1 ELSE 0 END) AS syphilis_tested,
  SUM(CASE WHEN HIV_STI_CLIENTS_SYPHILIS_TESTED_POSITIVE_Y THEN 1 ELSE 0 END) AS syphilis_positive
FROM hiv_patient_events
WHERE event_date > :#lastSyncTimestamp AND org_unit = 'ImspTQPwCqd'
GROUP BY TO_CHAR(event_date, 'YYYYMM')
ORDER BY period
