-- Initialize LIM (Laboratory Information Management) database schema
-- This script creates the necessary tables for PCR test data from LIM systems

-- LIM Test Results Table
-- This table stores raw PCR test data from LIM systems
CREATE TABLE IF NOT EXISTS lims_test_results (
    id SERIAL PRIMARY KEY,
    test_date DATE NOT NULL,
    facility_id VARCHAR(255) NOT NULL,
    facility_name VARCHAR(255),
    test_type VARCHAR(100) NOT NULL DEFAULT 'PCR',
    patient_age INTEGER,
    patient_gender VARCHAR(10),
    test_result VARCHAR(50) NOT NULL, -- 'positive', 'negative', 'indeterminate'
    test_count INTEGER DEFAULT 1,
    period VARCHAR(50), -- Calculated period (e.g., '202401')
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    synced_at TIMESTAMP NULL
);

-- Create patient-level HIV events table with explicit columns
CREATE TABLE IF NOT EXISTS hiv_patient_events (
    id SERIAL PRIMARY KEY,
    event_date DATE NOT NULL,
    org_unit VARCHAR(255) NOT NULL,
    patient_age INTEGER,
    -- General demographic fields (TEXT)
    GEN_FAMILY_NAME TEXT,
    GEN_GIVEN_NAME TEXT,
    GEN_ADM_RESIDENCE_AREA TEXT,
    GEN_AGE_Y INTEGER,
    GEN_BIRTH_ATNDT TEXT,
    GEN_BIRTH_TYPE TEXT,
    GEN_BIRTH_WGHT INTEGER,
    GEN_CMPLT_WKS_PREG INTEGER,
    GEN_DEATH_DATE DATE,
    GEN_BIRTH_FAC TEXT,
    GEN_GESTAGE INTEGER,
    GEN_MANNER_DEATH TEXT,
    GEN_BIRTH_DLV TEXT,
    GEN_BIRTH_PARITY INTEGER,
    GEN_BIRTH_PLC TEXT,
    GEN_BIRTH_VLG TEXT,
    GEN_PREGNANCY_STATUS TEXT,
    GEN_PREGNANCY_TRIMESTER TEXT,
    GEN_SEX_W_UNK TEXT,
    GEN_UNKNOWN_BIRTH_WEIGHT BOOLEAN NOT NULL DEFAULT FALSE,
    GEN_UNKNOWN_GESTATIONAL_AGE BOOLEAN NOT NULL DEFAULT FALSE,
    -- Population counts (INTEGER)
    CH001a INTEGER,
    CH008 INTEGER,
    CH009 INTEGER,
    CH106b INTEGER,
    GEN_POP_NUM INTEGER,
    GEN_P0Y__P15Y INTEGER,
    GEN_P0Y__P1Y INTEGER,
    GEN_P0Y__P2Y INTEGER,
    GEN_P0Y__P5Y INTEGER,
    GEN_PREG_EXPECT INTEGER,
    GEN_F_15_19 INTEGER,
    GEN_LIVEBIRTH INTEGER,
    GEN_POP_NUM_W INTEGER,
    -- HIV service availability (BOOLEAN)
    HIV_HFP_ART_AVAILABLE BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_HFP_CD4_TESTING_AVAILABLE BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_HFP_TESTING_AVAILABLE BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_HFP_VIRAL_LOAD_TESTING_AVAILABLE BOOLEAN NOT NULL DEFAULT FALSE,
    -- HIV Cervical Cancer indicators (BOOLEAN)
    HIV_PLHIV_CC_RECEIVED_1_DOSE_HPV BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_WLHIV_DX_CERVICAL_CANCER_Y BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_WLHIV_DX_CERVICAL_CANCER_TREATED_Y BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_CERVICAL_CANCER_SCREENING_COVERAGE_PROP_Y BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_WLHIV_POS_CERVICAL_PRECANCER_LESIONS_Y BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_WLHIV_POS_CERV_PRECANCER_LESIONS_TREATMENT_Y BOOLEAN NOT NULL DEFAULT FALSE,
    -- HIV Condoms/Deaths/Estimation (INTEGER counts or BOOLEAN)
    HIV_CONDOMS_DISTRIBUTED_M INTEGER,
    HIV_AIDS_RELATED_DEATHS INTEGER,
    HIV_PLHIV_ESTIMATION INTEGER,
    -- Facility stockouts (INTEGER days)
    HF_WITH_HIV_TEST_KITS_STOCKOUT_DAYS_REPORTED INTEGER,
    HF_WITH_HIV_TREATMENT_COURSES_STOCKOUT_DAYS INTEGER,
    HF_WITHOUT_HIV_TEST_KITS_STOCKOUT_DAYS_REPORTED INTEGER,
    HF_WITHOUT_HIV_TX_COURSES_STOCKOUT_DAYS_REPORTED INTEGER,
    -- HIV Hepatitis testing (BOOLEAN or INTEGER counts)
    HIV_HEP_CLIENTS_TESTED_HBSAG_M INTEGER,
    HIV_HEP_CLIENTS_TESTED_HBSAG_Y INTEGER,
    HIV_HEP_CLIENTS_TESTED_HCV_M INTEGER,
    HIV_HEP_CLIENTS_TESTED_HCV_Y INTEGER,
    HIV_HEP_TST_HBSAG_POS_M INTEGER,
    HIV_HEP_TST_HBSAG_POS_Y INTEGER,
    HIV_HEP_TST_HCV_POS_M INTEGER,
    HIV_HEP_TST_HCV_POS_Y INTEGER,
    -- HIV Self-tests (INTEGER counts)
    HIV_ST_DRUG_INJECTION_PARTNER_Y INTEGER,
    HIV_ST_OTHER_Y INTEGER,
    HIV_ST_SELF_FACILITY_BASED_Y INTEGER,
    HIV_ST_SELF_NON_FACILITY_BASED_Y INTEGER,
    HIV_ST_SEX_PARTNER_Y INTEGER,
    HIV_ST_SOCIAL_CONTACT_Y INTEGER,
    -- HIV/TB indicators (BOOLEAN)
    HIV_TB_PLHIV_NEW_ART_DIAGNOSED_TB_Y BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_PLHIV_NEW_ART_DX_TB_INITIATED_TREATMENT_Y BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_PLHIV_NEW_ART_INVESTIGATED_TB_Y BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_PLHIV_NEW_ART_SCREENED_TB_Y BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_PLHIV_NEW_ART_SCREENED_POS_TB_Y BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_PLHIV_ART_TB_TREATMENT_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_PLHIV_ART_TB_DIAGNOSED_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_PLHIV_ART_COMPLETING_TPT_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_PLHIV_ART_ELIGIBLE_TPT_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_PLHIV_ART_ELIGIBLE_INITIATED_TPT_M BOOLEAN NOT NULL DEFAULT FALSE,
    -- TPT regimens (BOOLEAN)
    HIV_TB_TPT_REGIMEN_1HP_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_TPT_REGIMEN_3HP_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_TPT_REGIMEN_3RH_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_TPT_REGIMEN_4R_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_TPT_REGIMEN_6H_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_TPT_REGIMEN_9H_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_TPT_REGIMEN_OTHER_M BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_TB_TPT_REGIMEN_SIX_MONTHS_LEVOFLOXACIN_DAILY BOOLEAN NOT NULL DEFAULT FALSE,
    -- HIV test kits stock (INTEGER)
    HIV_HIVTEST_DISCARDED INTEGER,
    HIV_HIVTEST_ISSUED INTEGER,
    HIV_HIVTEST_OPENING_BALANCE INTEGER,
    HIV_HIVTEST_RECV INTEGER,
    HIV_HIVTEST_REDISTRIBUTED INTEGER,
    HIV_HIVTEST_HAND INTEGER,
    HIV_HIVTEST_STOCKOUT_DAYS INTEGER,
    -- HIV tests (INTEGER counts)
    HIV_TEST_M INTEGER,
    HIV_TEST_POS_M INTEGER,
    -- HIV treatment stock (INTEGER)
    HIV_HIVTX_DISCARDED INTEGER,
    HIV_HIVTX_ISSUED INTEGER,
    HIV_HIVTX_OPENING_BALANCE INTEGER,
    HIV_HIVTX_RECV INTEGER,
    HIV_HIVTX_REDISTRIBUTED INTEGER,
    HIV_HIVTX_HAND INTEGER,
    HIV_HIVTX_STOCKOUT_DAYS INTEGER,
    -- HTS indicators (INTEGER counts or BOOLEAN)
    HIV_HTS_PREV_INTERVENTION_7_DAYS_TEST_M INTEGER,
    HIV_HTS_PREV_INTERVENTION_7_DAYS_TEST_Y INTEGER,
    HIV_HTS_CLIENTS_TESTED_HIV_Y INTEGER,
    HIV_HTS_CLIENT_HIV_POSITIVE_Y INTEGER,
    HIV_HTS_COOMUNITY_TESTING BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_HTS_CT_Y INTEGER,
    HIV_HTS_FACILITY_TESTING BOOLEAN NOT NULL DEFAULT FALSE,
    HIV_HTS_HIV_POSITIVE_M INTEGER,
    HIV_HTS_HIV_TEST_PERFORMED_M INTEGER,
    HIV_HTS_HIVST_M INTEGER,
    -- HTS Key populations (INTEGER)
    HIV_HTS_HIV_TEST_RECEIVED_PWIDS_Y INTEGER,
    HIV_HTS_HIV_TEST_RECEIVED_CS_Y INTEGER,
    HIV_HTS_HIV_TEST_RECEIVED_MSM_Y INTEGER,
    HIV_HTS_HIV_TEST_RECEIVED_SWS_Y INTEGER,
    HIV_HTS_HIV_TEST_RECEIVED_TGS_Y INTEGER,
    HIV_HTS_POS_DX_KPOP_MSM_Y INTEGER,
    HIV_HTS_POS_DX_KPOP_CS_Y INTEGER,
    HIV_HTS_POS_DX_KPOP_PWIDS_Y INTEGER,
    HIV_HTS_POS_DX_KPOP_SWs_Y INTEGER,
    HIV_HTS_POS_DX_KPOP_TGS_Y INTEGER,
    HIV_HTS_RSK_HIV_NEG_M INTEGER,
    HIV_HTS_RSK_HIV_NEG_Y INTEGER,
    HIV_HTS_RSK_HTS2_M INTEGER,
    HIV_HTS_RSK_HTS2_Y INTEGER,
    -- New HIV cases (INTEGER)
    HIV_NEW_CASES_M INTEGER,
    HIV_KPOP_NEW_HIV_CASES_MSM_AGG_M INTEGER,
    HIV_KPOP_NEW_HIV_CASES_MULTIPLE_AGG_M INTEGER,
    HIV_KPOP_NEW_HIV_CASES_ONE_MORE_GROUPS_AGG_M INTEGER,
    HIV_KPOP_NEW_HIV_CASES_PRISON_AGG_M INTEGER,
    HIV_KPOP_NEW_HIV_CASES_IDU_AGG_M INTEGER,
    HIV_KPOP_NEW_HIV_CASES_SW_AGG_M INTEGER,
    HIV_KPOP_NEW_HIV_CASES_TG_AGG_M INTEGER,
    HIV_NEW_HIV_CASES_STARTED_ART_M INTEGER,
    HIV_NEW_CASES_STARTED_ART_SAME_DAY_DIAGNOSIS_M INTEGER,
    HIV_NEW_CASES_STARTED_ART_7_DAYS_M INTEGER,
    -- NSP indicators (INTEGER)
    HIV_NSP_ACCESS_SERVICE INTEGER,
    HIV_NSP_DIST INTEGER,
    HIV_NSP_NEEDLE_SYRINGE_RECIPIENTS INTEGER,
    -- OAMT indicators (INTEGER)
    HIV_OAMT INTEGER,
    HIV_OAMT_MAINTENANCE_DOSE INTEGER,
    HIV_OAMT_MIN_MD INTEGER,
    HIV_OAMT_RTT INTEGER,
    HIV_OAMT_STARTING INTEGER,
    HIV_OAMT_ACCESS INTEGER,
    HIV_OAMT_TIME INTEGER,
    -- PEP indicators (INTEGER)
    HIV_PEP_RECIPIENTS_M INTEGER,
    HIV_PEP_RECIPIENTS_Y INTEGER,
    HIV_PEP_CLIENTS_COMPLETING_PEP INTEGER,
    HIV_PEP_EXPECTED_TO_BE_COMPLETED INTEGER,
    HIV_PEP_PRESCRIBED_MSM INTEGER,
    HIV_PEP_PRESCRIBED_CS INTEGER,
    HIV_PEP_PRESCRIBED_PWIDS INTEGER,
    HIV_PEP_PRESCRIBED_SWS INTEGER,
    HIV_PEP_PRESCRIBED_TGS INTEGER,
    HIV_PEP_TST_HIV_POS_MSM INTEGER,
    HIV_PEP_TST_HIV_POS_CS INTEGER,
    HIV_PEP_TST_HIV_POS_PWIDS INTEGER,
    HIV_PEP_TST_HIV_POS_SWS INTEGER,
    HIV_PEP_TST_HIV_POS_TGs INTEGER,
    HIV_PEP_TST_HIV_POS INTEGER,
    -- PLHIV indicators (INTEGER)
    HIV_PLHIV_ACCESSING_HIV_SERVICES_Y INTEGER,
    HIV_ART_AT_6_MONTHS_VL_TESTED INTEGER,
    HIV_ART_6_MONTHS_VL_TESTED INTEGER,
    HIV_KPOP_PLHIV_VISIT_CASES_MSM_AGG_Y INTEGER,
    HIV_KPOP_PLHIV_VISIT_CASES_PRISON_AGG_Y INTEGER,
    HIV_KPOP_PLHIV_VISIT_CASES_IDU_AGG_Y INTEGER,
    HIV_KPOP_PLHIV_VISIT_CASES_SW_AGG_Y INTEGER,
    HIV_KPOP_PLHIV_VISIT_CASES_TG_AGG_Y INTEGER,
    HIV_PLHIV_ELIGIBLE_DSD_ART_Y INTEGER,
    HIV_PLHIV_ENROLLED_DSD_ART_Y INTEGER,
    HIV_PLHIV_ENROLLED_DSD_ART_VL_Y INTEGER,
    HIV_PLHIV_ENROLLED_DSD_ART_VL_SUPPRESSED_Y INTEGER,
    HIV_PLHIV_START_ART_BASELINE_CD4_M INTEGER,
    HIV_PLHIV_START_ART_BASELINE_CD4_LESS_200_M INTEGER,
    HIV_PLHIV_COHORT_M INTEGER,
    HIV_ART_M INTEGER,
    HIV_PLHIV_ON_ART_END_PREVIOUS_MONTH INTEGER,
    HIV_PLHIV_ON_ART_MORE_6_MONTHS INTEGER,
    HIV_PLHIV_ON_ART_6_MONTHS INTEGER,
    HIV_PLHIV_TREATMENT_STATUS_INITIATION_OLD_M INTEGER,
    HIV_PLHIV_TREATMENT_STATUS_INITIATION_NEW_M INTEGER,
    HIV_PLHIV_TREATMENT_STATUS_ON_ART_M INTEGER,
    HIV_PLHIV_TREATMENT_STATUS_REFUSED_M INTEGER,
    HIV_PLHIV_TREATMENT_STATUS_STOPPED_M INTEGER,
    HIV_VIRSUPP_M INTEGER,
    HIV_PLHIV_3_5_MONTHS_ART_M INTEGER,
    HIV_PLHIV_3_5_MONTHS_ART_Y INTEGER,
    HIV_PLHIV_MORE_6_MONTHS_ART_M INTEGER,
    HIV_PLHIV_MORE_6_MONTHS_ART_Y INTEGER,
    -- PMTCT indicators (INTEGER)
    HIV_PMTCT_HIV_EXP_INF_BORNED_LAST_12_M_Y INTEGER,
    HIV_PMTCT_HIV_EXP_INF_ART_PROPH_BIRTH_Y INTEGER,
    HIV_PMTCT_HIV_EXP_INF_VIR_HIV_TEST_2_M_Y INTEGER,
    HIV_PMTCT_HIV_EXP_INF_LAST_12_M_KNOW_HIV_STAT_Y INTEGER,
    HIV_PMTCT_HIV_POS_DELIVER_LAST_12_M_Y INTEGER,
    HIV_PMTCT_PW_ART_DELIVERED_VIRAL_SUPPRESSED_Y INTEGER,
    HIV_PMTCT_PW_ART_DELIVERED_Y INTEGER,
    -- Population estimations (INTEGER)
    HIV_POPULATION_ESTIMATION_PREP_ELIGIBLE INTEGER,
    HIV_ESTIMATES_POP_HIV_POS_WOMEN_DELIVERED INTEGER,
    HIV_ESTIMATES_POP_HIV_UNINFECTED INTEGER,
    HIV_POPULATION_ESTIMATION_OPIOID_DEP INTEGER,
    HIV_POPULATION_ESTIMATION_PWID INTEGER,
    HIV_POPULATION_ESTIMATION_UNINFECTED INTEGER,
    -- PrEP indicators (INTEGER)
    HIV_PREP_DISTRIBUTED_M INTEGER,
    HIV_PREP_TEST_PROVIDER_ADMINISTERES INTEGER,
    HIV_PREP_TEST_SELF INTEGER,
    HIV_PREP_TEST_UNKNOWN INTEGER,
    HIV_PREP_RECIPIENTS_Y INTEGER,
    HIV_PREP_RECIPIENTS_MSM_Y INTEGER,
    HIV_PREP_RECIPIENTS_CS_Y INTEGER,
    HIV_PREP_RECIPIENTS_PWIDS_Y INTEGER,
    HIV_PREP_RECIPIENTS_SWS_Y INTEGER,
    HIV_PREP_RECIPIENTS_TGs_Y INTEGER,
    -- Probable transmission routes (TEXT)
    HIV_PROB_TRANSMISSION_HETEROSEXUAL_SEX_M TEXT,
    HIV_PROB_TRANSMISSION_MULTIPLE_M TEXT,
    HIV_PROB_TRANSMISSION_NOSOCOMIAL_M TEXT,
    HIV_PROB_TRANSMISSION_OTHER_M TEXT,
    HIV_PROB_TRANSMISSION_SEX_BETW_MEN_M TEXT,
    HIV_PROB_TRANSMISSION_VERTICAL_M TEXT,
    HIV_PROB_TRANSMISSION_INJECTING_DRUGS_M TEXT,
    HIV_PROB_TRANSMISSION_UNPROTECTED_SEX_M TEXT,
    -- STI indicators (INTEGER)
    HIV_STI_CLIENTS_DIAGNOSES_STI_SYNDR_M INTEGER,
    HIV_STI_CLIENTS_DIAGNOSES_STI_SYNDROME_Y INTEGER,
    HIV_STI_CLIENTS_DX_STI_SYNDR_SAME_MORE_ONCE_M INTEGER,
    HIV_STI_CLIENTS_DX_STI_SYNDR_SAME_MORE_ONCE_Y INTEGER,
    HIV_STI_CLIENTS_GONORRHOEA_TESTED_M INTEGER,
    HIV_STI_CLIENTS_GONORRHOEA_TESTED_Y INTEGER,
    HIV_SYPHILIS_TESTED_MSM INTEGER,
    HIV_STI_CLIENTS_SYPHILIS_TESTED_M INTEGER,
    HIV_PP_SYPHILIS_TESTED_LIVING_CLOSED_SETTINGS INTEGER,
    HIV_SYPHILIS_TESTED_PP_INJECT_DRUGS INTEGER,
    HIV_SYPHILIS_TESTED_SEX_WORKERS INTEGER,
    HIV_SYPHILIS_TESTED_TRANS_GENDER_DIVERSE INTEGER,
    HIV_STI_CLIENTS_SYPHILIS_TESTED_Y INTEGER,
    HIV_STI_CLIENTS_GONORRHOEA_TESTED_POSITIVE_M INTEGER,
    HIV_STI_CLIENTS_GONORRHOEA_TESTED_POSITIVE_Y INTEGER,
    HIV_STI_CLIENTS_SYPHILIS_TESTED_POSITIVE_M INTEGER,
    HIV_STI_CLIENTS_SYPHILIS_TESTED_POSITIVE_Y INTEGER,
    HIV_STI_CLIENTS_GONORRHOEA_TESTED_POS_TREATED INTEGER,
    HIV_STI_CLIENTS_SYPHILIS_TESTED_POS_TREATED INTEGER,
    HIV_STI_GONO_TST_MSM INTEGER,
    HIV_STI_GONO_TST_CS INTEGER,
    HIV_STI_GONO_TST_PWIDS INTEGER,
    HIV_STI_GONO_TST_SW INTEGER,
    HIV_STI_GONO_TST_TGs INTEGER,
    -- STI PLHIV indicators (INTEGER)
    HIV_STI_PLHIV_SAME_STI_SYND_LAST_12_M_MORE_ONCE_M INTEGER,
    HIV_STI_PLHIV_SAME_STI_SYND_LAST_12_M_MORE_ONCE_Y INTEGER,
    HIV_STI_PLHIV_DX_STI_SYNDROME_Y INTEGER,
    HIV_STI_PLHIV_DX_STI_SYNDROME_LAST_12_MONTHS_M INTEGER,
    HIV_STI_PLHIV_DX_STI_SYNDROME_LAST_12_MONTHS_Y INTEGER,
    HIV_STI_PLHIV_KPOP_GONORRHOEA_TEST_MSM_AGG_Y INTEGER,
    HIV_STI_PLHIV_KPOP_GONORRHOEA_TEST_PRIS_AGG_Y INTEGER,
    HIV_STI_PLHIV_KPOP_GONORRHOEA_TEST_IDU_AGG_Y INTEGER,
    HIV_STI_PLHIV_KPOP_GONORRHOEA_TEST_SW_AGG_Y INTEGER,
    HIV_STI_PLHIV_KPOP_GONORRHOEA_TEST_TG_AGG_Y INTEGER,
    HIV_STI_GONORRHOEA_TESTED_M INTEGER,
    HIV_STI_GONORRHOEA_TESTED_Y INTEGER,
    HIV_STI_PLHIV_STI_KPOP_SYPHILIS_TEST_MSM_AGG_Y INTEGER,
    HIV_STI_PLHIV_STI_KPOP_SYP_TEST_PRISON_AGG_Y INTEGER,
    HIV_STI_PLHIV_STI_KPOP_SYPHILIS_TEST_IDU_AGG_Y INTEGER,
    HIV_STI_PLHIV_STI_KPOP_SYPHILIS_TEST_SW_AGG_Y INTEGER,
    HIV_STI_PLHIV_STI_KPOP_SYPHILIS_TEST_TG_AGG_Y INTEGER,
    HIV_STI_SYPHILIS_TESTED_M INTEGER,
    HIV_STI_SYPHILIS_TESTED_Y INTEGER,
    HIV_STI_GONORRHOEA_TESTED_POSITIVE_M INTEGER,
    HIV_STI_GONORRHOEA_TESTED_POSITIVE_Y INTEGER,
    HIV_STI_SYPHILIS_TESTED_POSITIVE_M INTEGER,
    HIV_STI_SYPHILIS_TESTED_POSITIVE_Y INTEGER,
    HIV_STI_GONORRHOEA_TREATED_Y INTEGER,
    HIV_STI_SYPHILIS_TREATED_Y INTEGER,
    -- Viral hepatitis PLHIV indicators (INTEGER)
    HIV_PLHIV_VH_HCV_COMPL_TX_SUSTAINED_VIR_RESP_Y INTEGER,
    HIV_PLHIV_VH_HCV_COMPLETE_TX_ASSESSED_VIR_RESP_Y INTEGER,
    HIV_PLHIV_VH_HBV_STARTING_TREATMENT_Y INTEGER,
    HIV_PLHIV_VH_HCV_STARTING_TREATMENT_Y INTEGER,
    HIV_PLHIV_VH_HBV_TESTED_M INTEGER,
    HIV_PLHIV_VH_HBV_TESTED_Y INTEGER,
    HIV_PLHIV_VH_HCV_TESTED_M INTEGER,
    HIV_PLHIV_VH_HCV_TESTED_Y INTEGER,
    HIV_PLHIV_VH_HBV_TESTED_POSITIVE_M INTEGER,
    HIV_PLHIV_VH_HBV_TESTED_POSITIVE_Y INTEGER,
    HIV_PLHIV_VH_HCV_TESTED_POSITIVE_M INTEGER,
    HIV_PLHIV_VH_HCV_TESTED_POSITIVE_Y INTEGER,
    -- VMMC indicators (INTEGER)
    HIV_VMMC_AE INTEGER,
    HIV_VMMC_M INTEGER,
    HIV_VMMC_Y INTEGER,
    -- Volume indicators (INTEGER)
    HIV_CLIENTS_ATTENDING_M INTEGER,
    HIV_CLIENTS_ATTENDING_Y INTEGER,
    HIV_CLIENTS_ATTENDING_MSM INTEGER,
    HIV_CLIENTS_ATTENDING_CLOSED_SETTINGS INTEGER,
    HIV_CLIENTS_ATTENDING_PID INTEGER,
    HIV_CLIENTS_ATTENDING_SEX_WORKERS INTEGER,
    HIV_CLIENTS_ATTENDING_TRANS INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for patient-level events
CREATE INDEX IF NOT EXISTS idx_hiv_patient_events_event_date ON hiv_patient_events(event_date);
CREATE INDEX IF NOT EXISTS idx_hiv_patient_events_org_unit ON hiv_patient_events(org_unit);
CREATE INDEX IF NOT EXISTS idx_hiv_patient_events_patient_age ON hiv_patient_events(patient_age);


-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_lims_test_results_period ON lims_test_results(period);
CREATE INDEX IF NOT EXISTS idx_lims_test_results_facility ON lims_test_results(facility_id);
CREATE INDEX IF NOT EXISTS idx_lims_test_results_test_date ON lims_test_results(test_date);
CREATE INDEX IF NOT EXISTS idx_lims_test_results_test_type ON lims_test_results(test_type);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_lims_test_results_updated_at BEFORE UPDATE
    ON lims_test_results FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Function to calculate period from test_date (YYYYMM format)
CREATE OR REPLACE FUNCTION calculate_period(test_date DATE)
RETURNS VARCHAR(50) AS $$
BEGIN
    RETURN TO_CHAR(test_date, 'YYYYMM');
END;
$$ LANGUAGE plpgsql;

-- Update period for existing records (if any)
UPDATE lims_test_results SET period = calculate_period(test_date) WHERE period IS NULL;
